apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-analytics-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-analytics-service-green
  template:
    metadata:
      labels:
        app: lugx-analytics-service-green
    spec:
      containers:
      - name: lugx-analytics-service
        image: 476287788277.dkr.ecr.ap-south-1.amazonaws.com/lugx-analytics-service
        ports:
        - containerPort: 3003
        env:
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: CLICKHOUSE_PORT
          value: "8123"
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: username
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-secret
              key: password

